spring.application.name=condensation

auth.service.url=${AUTH_URL:http://localhost:8000}

spring.datasource.url=jdbc:postgresql://postgres-game:5432/game_db

spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=validate

internal.secret=${INTERNAL_SECRET:changeme}
